name: env_setup
on: [pull_request, push] 
branches: [main, dev]


env:
  ## Sets environment variable
  GIT_DEV: true

jobs:
  job1:
    runs-on: ubuntu-latest 
    steps:
      - name: step 1
        run: echo "Dev Env --> ${{GIT_DEV}}"   


